spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        # stdio: true # 禁用Stdio，启用Streamable HTTP
        protocol: STREAMABLE
        type: sync
        streamable-http:
          mcp-endpoint: /mcp
#这里填写个人的APPID和APIKEY
nullbr:
  api:
    base-url: https://api.nullbr.eu.org
    app-id: app-id
    api-key: api-key

#这里填写个人的CMS地址,账号和密码
cms:
  base-url: baseurl
  username: username
  password: password